# Generated by Django 6.1 on 2026-08-28 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='logged_at',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='servings_eaten',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs_g',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fats_g',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein_g',
        ),
        migrations.RemoveField(
            model_name='food',
            name='serving_size_g',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='servings',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.food'),
        ),
    ]
