# Generated by Django 6.1 on 2026-08-29 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_dailylog_logged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.food'),
        ),
    ]
