# Generated by Django 6.1 on 2026-08-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calorie_target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
